#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FinApps2014.Wearable.App.Resource", IsApplication=true)]

namespace FinApps2014.Wearable.App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int cadence_names = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cadence_names_km = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cadence_values = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int history_spinner = 2130968579;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int ab_white = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int blue_background = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int red_background = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int paddingBottom = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int standard_padding = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_highscore = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_notification = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_unsupporteddevice = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_warning = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int lacaixa_icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000c
			public const int calories = 2131296268;
			
			// aapt resource value: 0x7f090005
			public const int counter_layout = 2131296261;
			
			// aapt resource value: 0x7f09000e
			public const int distance = 2131296270;
			
			// aapt resource value: 0x7f09000a
			public const int high_score = 2131296266;
			
			// aapt resource value: 0x7f090006
			public const int lacaixa_icon = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int no_sensor_box = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int no_sensor_image = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int no_step_sensor = 2131296260;
			
			// aapt resource value: 0x7f09000b
			public const int percentage = 2131296267;
			
			// aapt resource value: 0x7f090000
			public const int progressView = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int stepcount = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int steps = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int today = 2131296263;
			
			// aapt resource value: 0x7f090001
			public const int top_layer = 2131296257;
			
			// aapt resource value: 0x7f09000d
			public const int warning = 2131296269;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int about = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int about_title = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f07003a
			public const int awesome = 2131165242;
			
			// aapt resource value: 0x7f070038
			public const int awesome_title = 2131165240;
			
			// aapt resource value: 0x7f070022
			public const int cadence = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int cadence0 = 2131165219;
			
			// aapt resource value: 0x7f07002a
			public const int cadence0_km = 2131165226;
			
			// aapt resource value: 0x7f070024
			public const int cadence1 = 2131165220;
			
			// aapt resource value: 0x7f07002b
			public const int cadence1_km = 2131165227;
			
			// aapt resource value: 0x7f070025
			public const int cadence2 = 2131165221;
			
			// aapt resource value: 0x7f07002c
			public const int cadence2_km = 2131165228;
			
			// aapt resource value: 0x7f070026
			public const int cadence3 = 2131165222;
			
			// aapt resource value: 0x7f07002d
			public const int cadence3_km = 2131165229;
			
			// aapt resource value: 0x7f070027
			public const int cadence4 = 2131165223;
			
			// aapt resource value: 0x7f07002e
			public const int cadence4_km = 2131165230;
			
			// aapt resource value: 0x7f070028
			public const int cadence5 = 2131165224;
			
			// aapt resource value: 0x7f07002f
			public const int cadence5_km = 2131165231;
			
			// aapt resource value: 0x7f070029
			public const int cadence6 = 2131165225;
			
			// aapt resource value: 0x7f070030
			public const int cadence6_km = 2131165232;
			
			// aapt resource value: 0x7f07000f
			public const int calories = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int calories_short = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int category_general_preferences = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int category_notifications_preferences = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int completed = 2131165198;
			
			// aapt resource value: 0x7f07001d
			public const int copyright = 2131165213;
			
			// aapt resource value: 0x7f070019
			public const int created_by = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int created_by_summary = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int created_with = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int created_with_summary = 2131165216;
			
			// aapt resource value: 0x7f070041
			public const int custom_step_goal = 2131165249;
			
			// aapt resource value: 0x7f070017
			public const int enhanced = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int enhanced_summary = 2131165208;
			
			// aapt resource value: 0x7f070035
			public const int goal_double = 2131165237;
			
			// aapt resource value: 0x7f070034
			public const int goal_full = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int goal_half = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int goal_update = 2131165238;
			
			// aapt resource value: 0x7f070039
			public const int high_score = 2131165241;
			
			// aapt resource value: 0x7f070037
			public const int high_score_title = 2131165239;
			
			// aapt resource value: 0x7f07001b
			public const int inspired_by = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int inspired_by_summary = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int kilometeres = 2131165202;
			
			// aapt resource value: 0x7f070032
			public const int menu_history = 2131165234;
			
			// aapt resource value: 0x7f070001
			public const int menu_settings = 2131165185;
			
			// aapt resource value: 0x7f07003c
			public const int menu_share = 2131165244;
			
			// aapt resource value: 0x7f070011
			public const int miles = 2131165201;
			
			// aapt resource value: 0x7f070044
			public const int month = 2131165252;
			
			// aapt resource value: 0x7f070031
			public const int no_history = 2131165233;
			
			// aapt resource value: 0x7f070042
			public const int no_step_sensor = 2131165250;
			
			// aapt resource value: 0x7f070008
			public const int notifications_accumulative = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notifications_accumulative_summary = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int notifications_progress = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int notifications_progress_summary = 2131165191;
			
			// aapt resource value: 0x7f070021
			public const int ok = 2131165217;
			
			// aapt resource value: 0x7f07000d
			public const int percent_complete = 2131165197;
			
			// aapt resource value: 0x7f07003f
			public const int review_app = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int review_app_summary = 2131165248;
			
			// aapt resource value: 0x7f07003b
			public const int share_steps_on = 2131165243;
			
			// aapt resource value: 0x7f07003d
			public const int share_steps_today = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int share_steps_total = 2131165246;
			
			// aapt resource value: 0x7f07000a
			public const int steps = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int steps_cap = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int today = 2131165196;
			
			// aapt resource value: 0x7f070045
			public const int total = 2131165253;
			
			// aapt resource value: 0x7f07001e
			public const int version = 2131165214;
			
			// aapt resource value: 0x7f070043
			public const int week = 2131165251;
			
			// aapt resource value: 0x7f070013
			public const int weight_kg = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int weight_lbs = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int weight_title_kg = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int weight_title_lbs = 2131165206;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080004
			public const int Mono_Android_Theme_Splash = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int MyTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MyTheme_ActionBar = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int ThemeActionBar = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
